#!/bin/sh
### BEGIN INIT INFO
# Provides:          reddit2tg
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Reddit Chat to Telegram bridge
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=/usr/bin/reddit2tg
[ -x "$DAEMON" ] || DAEMON=/usr/local/bin/reddit2tg
NAME=reddit2tg
DESC="Reddit Chat to Telegram bridge"
PIDDIR=/run/$NAME
PIDFILE=$PIDDIR/$NAME.pid
USER=reddit2tg
CONFIG=/etc/reddit2tg/config.toml
LOGFILE=/var/log/reddit2tg.log

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    install -d -o "$USER" -g "$USER" -m 0755 "$PIDDIR"
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile "$PIDFILE" --chuid "$USER" --startas /bin/sh -- -c "exec $DAEMON --config $CONFIG run >>$LOGFILE 2>&1"
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --stop --quiet --retry=TERM/20/KILL/5 --pidfile "$PIDFILE"
    rc=$?
    rm -f "$PIDFILE"
    log_end_msg "$rc"
    ;;
  restart|force-reload)
    "$0" stop
    "$0" start
    ;;
  status)
    status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME"
    exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
    exit 2
    ;;
esac
exit 0
